### ISSUE TITLE
Properly set defaults and fix undeclared variable.

### ISSUE THREAD

**Issue by lliss** [mojodna/tilelive-streaming#3]
The application currently breaks in some cases. I was using it with ```tl``` (https://github.com/mojodna/tl) and found that I was getting an error looking for ```concurrency``` on an undefined ```options```.

Additionally the ```CONCURRENCY``` variable (https://github.com/mojodna/tilelive-streaming/blob/c2750f47fb36d1dba6faae452a51cc61efca72a3/index.js#L139) was never properly declared.

**Comment by mojodna** [comment]
Woops, that wasn't supposed to leak in.  Thanks for spotting this.
